services:
  ui:
    container_name: ui
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4173:4173
      - 5173:5173
    networks:
      - flora-network
  db:
    image: mysql:latest
    container_name: db
    env_file:
      - .env.development
    environment:
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_DATABASE: test
      # MYSQL_USER: test
      # MYSQL_PASSWORD: test
    ports:
      - 3306:3306
    volumes:
      - flora-db:/var/lib/mysql
      - ./db-init-scripts:/docker-entrypoint-initdb.d
    networks:
      - flora-network

volumes:
  flora-db:
    name: "flora-db" 

networks:
  flora-network:
    name: "flora-network"
    driver: "bridge"