# Base your container on a Debian-based Rust image
FROM ubuntu:latest

# Create a new user called 'developer' and add to sudoers
ARG USERNAME=dev
ARG USER_UID=1020
ARG USER_GID=$USER_UID
ARG HOME=/home/$USERNAME
ARG PROJECT=flora

WORKDIR /workspace/$PROJECT
RUN apt-get update && apt-get install -y \
vim \
    zsh \
    curl \
    sudo \
    libssl-dev \
    unzip \
    git \
    mysql-client
# Create the user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m -s /usr/bin/zsh $USERNAME


# [Optional] Add sudo support. Omit if you don't need to install software after connecting.
RUN echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME \
    && mkdir -p /workspace/$PROJECT \
    && chown -R $USERNAME:$USERNAME /workspace

## Enter the 'developer' user
USER $USERNAME
RUN curl -fsSL https://bun.sh/install | bash

# Install Oh My Zsh for the 'developer' user
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended \
    && [ -d "/home/$USERNAME/.oh-my-zsh" ] && echo "Oh My Zsh installed successfully" || echo "Oh My Zsh installation failed"
# Uses "Spaceship" theme with some customization. Uses some bundled plugins and installs some more from github
RUN sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v1.2.1/zsh-in-docker.sh)" -- \
    -t https://github.com/denysdovhan/spaceship-prompt \
    -a 'SPACESHIP_PROMPT_ADD_NEWLINE="false"' \
    -a 'SPACESHIP_PROMPT_SEPARATE_LINE="false"' \
    -p git \
    -p ssh-agent \
    -p https://github.com/zsh-users/zsh-autosuggestions \
    -p https://github.com/zsh-users/zsh-completions
# Set the default editor to vi
ENV EDITOR=vim
RUN zsh -c "curl -sSfL https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | sh" \
    && echo 'eval "$(zoxide init zsh)"' >> /home/$USERNAME/.zshrc

ENV PATH=$PATH:$HOME/.local/bin:$HOME/.bun/bin
# RUN source in devcontainer (best-practice)