services:
  ui:
    build: 
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - ../:/workspace:cached
    ports:
      - 5173:5173
      - 4173:4173
      

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:db # network is already bridge type in compose.yml

